name: zeswen_web
description: My own website with all the details of my career.
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  url_launcher: ^6.0.13
  url_launcher_web: ^2.0.4
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/light/
    - assets/images/dark/
    - assets/images/projects/
